services:
  - type: web
    name: wedding-app-api
    runtime: docker
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: wedding-db
          property: connectionString
      - key: PORT
        value: 3000

databases:
  - name: wedding-db
    region: oregon
    plan: free
    ipAllowList: []  # optional (allows all IPs by default)
